apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-training-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-training-app
  template:
    metadata:
      labels:
        app: devops-training-app
    spec:
      containers:
        - name: devops-training-container
          image: devops-training-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000